// {
//   _events: [Object: null prototype] { error: [Function: noop] },
//   _eventsCount: 1,
//   _maxListeners: undefined,
//   nsp: <ref *1> Namespace {
//     _events: [Object: null prototype] { connection: [Function (anonymous)] },
//     _eventsCount: 1,
//     _maxListeners: undefined,
//     sockets: Map(0) {},
//     _fns: [ [Function (anonymous)] ],
//     _ids: 0,
//     server: Server {
//       _events: [Object: null prototype] {},
//       _eventsCount: 0,
//       _maxListeners: undefined,
//       _nsps: [Map],
//       parentNsps: Map(0) {},
//       parentNamespacesFromRegExp: Map(0) {},
//       _path: '/socket.io',
//       clientPathRegex: /^\/socket\.io\/socket\.io(\.msgpack|\.esm)?(\.min)?\.js(\.map)?(?:\?|$)/,    

//       _connectTimeout: 45000,
//       _serveClient: true,
//       _parser: [Object],
//       encoder: [Encoder],
//       opts: [Object],
//       _adapter: [class Adapter extends EventEmitter],
//       sockets: [Circular *1],
//       eio: [Server],
//       httpServer: [Server],
//       engine: [Server],
//       _corsMiddleware: [Function: corsMiddleware],
//       [Symbol(shapeMode)]: false,
//       [Symbol(kCapture)]: false
//     },
//     name: '/',
//     adapter: Adapter {
//       _events: [Object: null prototype] {},
//       _eventsCount: 0,
//       _maxListeners: undefined,
//       nsp: [Circular *1],
//       rooms: Map(0) {},
//       sids: Map(0) {},
//       encoder: [Encoder],
//       [Symbol(shapeMode)]: false,
//       [Symbol(kCapture)]: false
//     },
//     [Symbol(shapeMode)]: false,
//     [Symbol(kCapture)]: false
//   },
//   client: Client {
//     sockets: Map(0) {},
//     nsps: Map(0) {},
//     server: Server {
//       _events: [Object: null prototype] {},
//       _eventsCount: 0,
//       _maxListeners: undefined,
//       _nsps: [Map],
//       parentNsps: Map(0) {},
//       parentNamespacesFromRegExp: Map(0) {},
//       _path: '/socket.io',
//       clientPathRegex: /^\/socket\.io\/socket\.io(\.msgpack|\.esm)?(\.min)?\.js(\.map)?(?:\?|$)/,    
//       _connectTimeout: 45000,
//       _serveClient: true,
//       _parser: [Object],
//       encoder: [Encoder],
//       opts: [Object],
//       _adapter: [class Adapter extends EventEmitter],
//       sockets: [Namespace],
//       eio: [Server],
//       httpServer: [Server],
//       engine: [Server],
//       _corsMiddleware: [Function: corsMiddleware],
//       [Symbol(shapeMode)]: false,
//       [Symbol(kCapture)]: false
//     },
//     conn: Socket {
//       _events: [Object: null prototype],
//       _eventsCount: 3,
//       _maxListeners: undefined,
//       id: '4soNCua50hwr93q6AAAE',
//       server: [Server],
//       upgrading: false,
//       upgraded: false,
//       _readyState: 'open',
//       writeBuffer: [],
//       packetsFn: [],
//       sentCallbackFn: [],
//       cleanupFn: [Array],
//       request: [IncomingMessage],
//       protocol: 4,
//       remoteAddress: '192.168.0.34',
//       checkIntervalTimer: null,
//       upgradeTimeoutTimer: null,
//       pingTimeoutTimer: Timeout {
//         _idleTimeout: 45000,
//         _idlePrev: [TimersList],
//         _idleNext: [Timeout],
//         _idleStart: 40953,
//         _onTimeout: [Function (anonymous)],
//         _timerArgs: undefined,
//         _repeat: null,
//         _destroyed: false,
//         [Symbol(refed)]: true,
//         [Symbol(kHasPrimitive)]: false,
//         [Symbol(asyncId)]: 82,
//         [Symbol(triggerId)]: 73
//       },
//       pingIntervalTimer: Timeout {
//         _idleTimeout: 25000,
//         _idlePrev: [TimersList],
//         _idleNext: [TimersList],
//         _idleStart: 40950,
//         _onTimeout: [Function (anonymous)],
//         _timerArgs: undefined,
//         _repeat: null,
//         _destroyed: false,
//         [Symbol(refed)]: true,
//         [Symbol(kHasPrimitive)]: false,
//         [Symbol(asyncId)]: 79,
//         [Symbol(triggerId)]: 0
//       },
//       transport: [WebSocket],
//       [Symbol(shapeMode)]: false,
//       [Symbol(kCapture)]: false
//     },
//     encoder: Encoder { replacer: undefined },
//     decoder: Decoder { reviver: undefined, _callbacks: [Object] },
//     id: '4soNCua50hwr93q6AAAE',
//     onclose: [Function: bound onclose],
//     ondata: [Function: bound ondata],
//     onerror: [Function: bound onerror],
//     ondecoded: [Function: bound ondecoded],
//     connectTimeout: Timeout {
//       _idleTimeout: 45000,
//       _idlePrev: [Timeout],
//       _idleNext: [TimersList],
//       _idleStart: 40950,
//       _onTimeout: [Function (anonymous)],
//       _timerArgs: undefined,
//       _repeat: null,
//       _destroyed: false,
//       [Symbol(refed)]: true,
//       [Symbol(kHasPrimitive)]: false,
//       [Symbol(asyncId)]: 80,
//       [Symbol(triggerId)]: 0
//     }
//   },
//   recovered: false,
//   data: {},
//   connected: false,
//   acks: Map(0) {},
//   fns: [],
//   flags: {},
//   server: <ref *2> Server {
//     _events: [Object: null prototype] {},
//     _eventsCount: 0,
//     _maxListeners: undefined,
//     _nsps: Map(1) { '/' => [Namespace] },
//     parentNsps: Map(0) {},
//     parentNamespacesFromRegExp: Map(0) {},
//     _path: '/socket.io',
//     clientPathRegex: /^\/socket\.io\/socket\.io(\.msgpack|\.esm)?(\.min)?\.js(\.map)?(?:\?|$)/,      
//     _connectTimeout: 45000,
//     _serveClient: true,
//     _parser: {
//       protocol: 5,
//       PacketType: [Object],
//       Encoder: [class Encoder],
//       Decoder: [class Decoder extends Emitter]
//     },
//     encoder: Encoder { replacer: undefined },
//     opts: { cors: [Object], cleanupEmptyChildNamespaces: false },
//     _adapter: [class Adapter extends EventEmitter],
//     sockets: <ref *1> Namespace {
//       _events: [Object: null prototype],
//       _eventsCount: 1,
//       _maxListeners: undefined,
//       sockets: Map(0) {},
//       _fns: [Array],
//       _ids: 0,
//       server: [Circular *2],
//       name: '/',
//       adapter: [Adapter],
//       [Symbol(shapeMode)]: false,
//       [Symbol(kCapture)]: false
//     },
//     eio: Server {
//       _events: [Object: null prototype],
//       _eventsCount: 1,
//       _maxListeners: undefined,
//       middlewares: [Array],
//       clients: [Object],
//       clientsCount: 1,
//       opts: [Object],
//       ws: [WebSocketServer],
//       [Symbol(shapeMode)]: false,
//       [Symbol(kCapture)]: false
//     },
//     httpServer: Server {
//       maxHeaderSize: undefined,
//       insecureHTTPParser: undefined,
//       requestTimeout: 300000,
//       headersTimeout: 60000,
//       keepAliveTimeout: 5000,
//       connectionsCheckingInterval: 30000,
//       requireHostHeader: true,
//       joinDuplicateHeaders: undefined,
//       rejectNonStandardBodyWrites: false,
//       _events: [Object: null prototype],
//       _eventsCount: 5,
//       _maxListeners: undefined,
//       _connections: 1,
//       _handle: [TCP],
//       _usingWorkers: false,
//       _workers: [],
//       _unref: false,
//       _listeningId: 2,
//       allowHalfOpen: true,
//       pauseOnConnect: false,
//       noDelay: true,
//       keepAlive: false,
//       keepAliveInitialDelay: 0,
//       highWaterMark: 16384,
//       httpAllowHalfOpen: false,
//       timeout: 0,
//       maxHeadersCount: null,
//       maxRequestsPerSocket: 0,
//       _connectionKey: '4:0.0.0.0:5000',
//       [Symbol(IncomingMessage)]: [Function: IncomingMessage],
//       [Symbol(ServerResponse)]: [Function: ServerResponse],
//       [Symbol(shapeMode)]: false,
//       [Symbol(kCapture)]: false,
//       [Symbol(async_id_symbol)]: 12,
//       [Symbol(kUniqueHeaders)]: null,
//       [Symbol(http.server.connections)]: ConnectionsList {},
//       [Symbol(http.server.connectionsCheckingInterval)]: Timeout {
//         _idleTimeout: 30000,
//         _idlePrev: [TimersList],
//         _idleNext: [TimersList],
//         _idleStart: 30123,
//         _onTimeout: [Function: bound checkConnections],
//         _timerArgs: undefined,
//         _repeat: 30000,
//         _destroyed: false,
//         [Symbol(refed)]: false,
//         [Symbol(kHasPrimitive)]: false,
//         [Symbol(asyncId)]: 14,
//         [Symbol(triggerId)]: 13
//       }
//     },
//     engine: Server {
//       _events: [Object: null prototype],
//       _eventsCount: 1,
//       _maxListeners: undefined,
//       middlewares: [Array],
//       clients: [Object],
//       clientsCount: 1,
//       opts: [Object],
//       ws: [WebSocketServer],
//       [Symbol(shapeMode)]: false,
//       [Symbol(kCapture)]: false
//     },
//     _corsMiddleware: [Function: corsMiddleware],
//     [Symbol(shapeMode)]: false,
//     [Symbol(kCapture)]: false
//   },
//   adapter: <ref *3> Adapter {
//     _events: [Object: null prototype] {},
//     _eventsCount: 0,
//     _maxListeners: undefined,
//     nsp: <ref *1> Namespace {
//       _events: [Object: null prototype],
//       _eventsCount: 1,
//       _maxListeners: undefined,
//       sockets: Map(0) {},
//       _fns: [Array],
//       _ids: 0,
//       server: [Server],
//       name: '/',
//       adapter: [Circular *3],
//       [Symbol(shapeMode)]: false,
//       [Symbol(kCapture)]: false
//     },
//     rooms: Map(0) {},
//     sids: Map(0) {},
//     encoder: Encoder { replacer: undefined },
//     [Symbol(shapeMode)]: false,
//     [Symbol(kCapture)]: false
//   },
//   id: 'EshY3-GO22_V3yXeAAAF',
//   handshake: {
//     headers: {
//       'user-agent': 'Dart/3.6 (dart:io)',
//       connection: 'Upgrade',
//       'cache-control': 'no-cache',
//       'accept-encoding': 'gzip',
//       'sec-websocket-version': '13',
//       host: '192.168.0.34:5000',
//       authorization: '1',
//       'sec-websocket-extensions': 'permessage-deflate; client_max_window_bits',
//       'sec-websocket-key': 'N9zGiaF7QirbgHWmbowLMQ==',
//       upgrade: 'websocket'
//     },
//     time: 'Wed Apr 30 2025 18:17:41 GMT+0500 (Pakistan Standard Time)',
//     address: '192.168.0.34',
//     xdomain: false,
//     secure: false,
//     issued: 1746019061452,
//     url: '/socket.io/?EIO=4&transport=websocket',
//     query: [Object: null prototype] { EIO: '4', transport: 'websocket' },
//     auth: {}
//   },
//   [Symbol(shapeMode)]: false,
//   [Symbol(kCapture)]: false
// }